package models

const SCENE_TYPE_SMS_SIGNUP = "SMS_SIGNUP"
const SCENE_TYPE_SMS_LOGIN = "SMS_LOGIN"
const ACCOUNT_ID_GEN_START = int64(65536 * 65536)
const ACCOUNT_ID_GEN_STEP = int64(256)
const SCOPE_ROOT  ="ROOT"
const OAUTH_ACCESS_TOKEN_EXPIRE_SECONDS=600
